const {createClient}=supabase;
const SUPABASE_URL='https://nrnrmbjrczmzkgimxdun.supabase.co';
const SUPABASE_KEY='sb_publishable_Lrb0SZIai9FwSYy0oDbnzg_vZ4BTakA';
const AUTH_URL=SUPABASE_URL+'/functions/v1/naskhah-v1-auth';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stripHtml=s=>{const d=document.createElement('div');d.innerHTML=String(s||'');return d.textContent||d.innerText||''};
const countWords=s=>{const t=stripHtml(s).trim();return t?t.split(/\s+/).length:0};
const reminderOptions=v=>Array.from({length:30},(_,i)=>`<option value="${i+1}" ${Number(v||7)===i+1?'selected':''}>${i+1} hari sebelum</option>`).join('');
const templates={
 article:{label:'Artikel Jurnal',target:10000,sections:['Abstract','Keywords','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion','Acknowledgement','References'],phases:[['Persediaan Kajian',['Tentukan topik','Research problem','Research gap','Research questions','Objectives','Target journal']],['Rangka Artikel',['Title','Abstract','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion']],['Research & Sources',['Collect references','Review papers','Save DOI','Organize citations','Figures / tables']],['Menulis',['Abstract','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion']],['Academic Editing',['Grammar','Academic tone','Argument flow','Citation check','Similarity check','Word count']],['Review',['Co-author review','Supervisor review','Peer feedback','Revision']],['Submission',['Journal formatting','Cover letter','Author details','References','Submission checklist','Submit','Revision tracking']]]},
 thesis:{label:'Tesis',target:70000,sections:['Abstract','Acknowledgement','Chapter 1: Introduction','Chapter 2: Literature Review','Chapter 3: Methodology','Chapter 4: Results / Findings','Chapter 5: Discussion','Chapter 6: Conclusion & Recommendations','References','Appendices'],phases:[['Persediaan',['Tentukan topik','Research problem','Research gap','Research questions','Objectives','Scope','Supervisor discussion']],['Rangka Tesis',['Abstract','Introduction','Literature Review','Methodology','Results / Findings','Discussion','Conclusion & Recommendations']],['Research & Data',['Ethics approval jika perlu','Data collection','Reference management','Figures / tables','Data analysis plan']],['Menulis',['Chapter 1','Chapter 2','Chapter 3','Chapter 4','Chapter 5','Chapter 6']],['Suntingan Akademik',['Academic tone','Argument flow','Citation check','Formatting','Tables / figures','Word count']],['Semakan Penyelia',['Submit chapters','Receive feedback','Revision','Supervisor approval']],['Akhir & Submission',['Final proofreading','University formatting','Declaration / front matter','References','Appendices','Final thesis submission']]]},
 book:{label:'Buku',target:50000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Penutup'],phases:[['Persediaan',['Tentukan tujuan buku','Pembaca sasaran','Genre','Gaya penulisan','Target words','Deadline']],['Rangka Buku',['Tajuk','Bahagian','Bab','Subbab','Susun flow buku']],['Jadual',['Tarikh mula','Tarikh siap','Daily writing goal','Weekly writing target','Jadual bab']],['Menulis',['Tulis bab demi bab','Semak target words','Lengkapkan manuskrip']],['Suntingan',['Self edit','Grammar','Structure','Consistency','Fact checking']],['Maklum Balas',['Beta reader','Editor','Peer review','Feedback','Revision']],['Akhir',['Final proofread','Formatting','Cover','ISBN','Export','Publish']]]},
 ebook:{label:'eBook',target:15000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Checklist / Bonus','Penutup','CTA'],phases:[['Idea & Audience',['Tentukan masalah pembaca','Persona pembaca','Outcome eBook']],['Outline',['Tajuk','Bab','Subbab','Flow']],['Content Plan',['Research','Contoh','Visual','Jadual penulisan']],['Writing',['Draft setiap bab','Lengkapkan CTA','Semak target']],['Editing',['Bahasa','Flow','Kejelasan','Fact check']],['Design & Review',['Layout','Cover','Visual','Proofread','Feedback']],['Publishing',['Final PDF','EPUB','Landing copy','Publish']]]}
};
let state=window.NaskhahCore.createState();
let authCall,setSession,loadProfile,loadProjects;
let writingView,bindWriter,openTableDialog,uploadImage,hydrateImages;
let overviewView,deadlinesView,specialSubmissionView,outlineView,checklistView,notesView,referencesView,exportView;
let projectCard,renderDashboard,reminderCentre,renderProjects,openCreate,createProject,normalizeProject,openProject;
let renderProfile,bindGlobal;
let projectWords,projectPct,tabs,renderProject;
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(bad?' bad':'');clearTimeout(t._x);t._x=setTimeout(()=>t.className='toast',2600)}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');$('#modalContent').innerHTML=''}
window.closeModal=closeModal;
function showPublic(panel='login'){$('#public').classList.remove('hidden');$('#app').classList.add('hidden');$$('.auth-panel').forEach(x=>x.classList.add('hidden'));$('#'+panel+'Panel').classList.remove('hidden')}
async function enterApp(){await loadProjects();$('#public').classList.add('hidden');$('#app').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',state.profile?.role!=='admin');renderDashboard()}
function nav(name){$$('.sidebar [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(innerWidth<=820)toggleNav(false)}
function toggleNav(force){const app=$('#app'),on=force??!app.classList.contains('nav-open');app.classList.toggle('nav-open',on)}
function versionsView(p){const arr=p.goals.versions||[];return `<div class="card"><div class="card-head"><div><h2>Versions</h2><p class="muted">Simpan manuskrip secara manual dan buka semula bila diperlukan.</p></div><button class="btn primary" id="saveVersion">Simpan Manuskrip</button></div>${arr.length?arr.slice().reverse().map((v,ri)=>{const i=arr.length-1-ri;return `<div class="version-row"><div><b>${esc(v.name)}</b><div class="muted">${new Date(v.at).toLocaleString('ms-MY')}</div></div><div class="actions"><button class="btn small" data-openver="${i}">Buka</button><button class="btn small danger" data-delver="${i}">Delete</button></div></div>`}).join(''):'<p class="muted">Belum ada manuskrip disimpan.</p>'}</div>`}
async function saveProject(){const p=state.current;p.updated_at=new Date().toISOString();const {error}=await sb.from('nv1_projects').update({title:p.title,target_words:p.target_words,deadline:p.deadline,status:p.status,content:p.content,outline:p.outline,checklist:p.checklist,goals:p.goals,updated_at:p.updated_at}).eq('id',p.id);if(error)throw error;const idx=state.projects.findIndex(x=>x.id===p.id);if(idx>=0)state.projects[idx]=p}
function bindTab(tab){const p=state.current;if(tab==='overview'){const s=p.goals.submission||{},j=p.goals.journal||{};if($('#supStatus'))$('#supStatus').value=s.supervisor_status||'Belum dihantar';if($('#finalStatus'))$('#finalStatus').value=s.final_status||'Draft';if($('#articleStatus'))$('#articleStatus').value=j.status||'Draft';$('#saveGoals').onclick=async()=>{p.goals.daily=Number($('#goalDaily').value||0);p.goals.weekly=Number($('#goalWeekly').value||0);p.deadline=$('#projectDeadline').value||null;try{await saveProject();toast('Writing goal disimpan.')}catch(e){toast(e.message,true)}};$('#saveDeadlines').onclick=async()=>{$$('[data-dsec]').forEach(r=>p.goals.section_deadlines[r.dataset.dsec]={due_date:r.querySelector('.d-date').value,reminder_days:Number(r.querySelector('.d-rem').value),target_words:Number(r.querySelector('.d-target').value||0)});try{await saveProject();toast('Deadlines disimpan.')}catch(e){toast(e.message,true)}};if($('#saveSubmission'))$('#saveSubmission').onclick=async()=>{p.goals.submission={...p.goals.submission,supervisor_date:$('#supDate')?.value||'',supervisor_reminder:Number($('#supRem')?.value||7),supervisor_status:$('#supStatus')?.value||'',feedback_date:$('#supFeedback')?.value||'',final_date:$('#finalDate')?.value||'',final_reminder:Number($('#finalRem')?.value||7),final_status:$('#finalStatus')?.value||''};if(p.project_type==='article')p.goals.journal={name:$('#journalName').value.trim(),publisher:$('#journalPublisher').value.trim(),submission_date:$('#journalDate').value,reminder_days:Number($('#journalRem').value||7),status:$('#articleStatus').value};try{await saveProject();toast('Submission tracking disimpan.')}catch(e){toast(e.message,true)}};if($('#addRevision'))$('#addRevision').onclick=()=>{modal(`<h2>Add Revision</h2><label>Tajuk<input id="revTitle"></label><label>Notes<textarea id="revNotes" rows="4"></textarea></label><label>Status<select id="revStatus"><option>Open</option><option>In Progress</option><option>Completed</option></select></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="saveRev">Add</button></div>`);$('#saveRev').onclick=async()=>{p.goals.revisions.push({title:$('#revTitle').value.trim()||'Revision',notes:$('#revNotes').value.trim(),status:$('#revStatus').value,at:new Date().toISOString()});await saveProject();closeModal();renderProject('overview')}};$$('[data-delrev]').forEach(b=>b.onclick=async()=>{p.goals.revisions.splice(Number(b.dataset.delrev),1);await saveProject();renderProject('overview')})}
if(tab==='writing')bindWriter(p);if(tab==='outline'){$('#addOutline').onclick=async()=>{p.outline=p.outline||[];p.outline.push({id:crypto.randomUUID(),title:'Bab / Bahagian Baharu',notes:'',target_words:1000,status:'not_started',children:[],order:p.outline.length});await saveProject();renderProject('outline')};$$('.outline-row').forEach(r=>{const i=Number(r.dataset.oi),o=p.outline[i];r.querySelector('.ol-status').value=o.status||'not_started';r.querySelector('.ol-title').onchange=async e=>{o.title=e.target.value;await saveProject()};r.querySelector('.ol-notes').onchange=async e=>{o.notes=e.target.value;await saveProject()};r.querySelector('.ol-target').onchange=async e=>{o.target_words=Number(e.target.value||0);await saveProject()};r.querySelector('.ol-status').onchange=async e=>{o.status=e.target.value;await saveProject()};r.querySelector('.del-outline').onclick=async()=>{p.outline.splice(i,1);await saveProject();renderProject('outline')}})}
if(tab==='checklist'){$$('[data-check]').forEach(c=>c.onchange=async()=>{const [pi,ii]=c.dataset.check.split(':').map(Number);p.checklist[pi].items[ii].done=c.checked;await saveProject();renderProject('checklist')});$$('.add-check').forEach(b=>b.onclick=()=>{const text=prompt('Item checklist baharu');if(text){p.checklist[Number(b.dataset.pi)].items.push({id:crypto.randomUUID(),text,done:false});saveProject().then(()=>renderProject('checklist'))}})}
if(tab==='notes'){$('#addNote').onclick=()=>{p.goals.notes.push({title:'',body:''});renderProject('notes')};$$('.note-card').forEach(c=>{const i=Number(c.dataset.ni);c.querySelector('.save-note').onclick=async()=>{p.goals.notes[i]={title:c.querySelector('.note-title').value.trim(),body:c.querySelector('.note-body').value};await saveProject();toast('Research note disimpan.')};c.querySelector('.del-note').onclick=async()=>{p.goals.notes.splice(i,1);await saveProject();renderProject('notes')}})}
if(tab==='references'){$('#addRef').onclick=()=>{p.goals.references.push({title:'',style:'APA 7',text:''});renderProject('references')};$$('.reference-card').forEach(c=>{const i=Number(c.dataset.ri),r=p.goals.references[i];c.querySelector('.ref-style').value=r.style||'APA 7';c.querySelector('.save-ref').onclick=async()=>{p.goals.references[i]={title:c.querySelector('.ref-title').value.trim(),style:c.querySelector('.ref-style').value,text:c.querySelector('.ref-text').value};await saveProject();toast('Reference disimpan.')};c.querySelector('.del-ref').onclick=async()=>{p.goals.references.splice(i,1);await saveProject();renderProject('references')}});$$('[data-copyref]').forEach(b=>b.onclick=async()=>{const r=p.goals.references[Number(b.dataset.copyref)];await navigator.clipboard.writeText(r.text||r.title||'');toast('Citation disalin.')})}
if(tab==='versions'){$('#saveVersion').onclick=()=>{modal(`<h2>Simpan Manuskrip</h2><label>Nama versi<input id="verName" value="Manuskrip ${p.goals.versions.length+1}"></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="confirmVersion">Simpan</button></div>`);$('#confirmVersion').onclick=async()=>{p.goals.versions.push({name:$('#verName').value.trim()||'Manuskrip',at:new Date().toISOString(),content:structuredClone(p.content),outline:structuredClone(p.outline),checklist:structuredClone(p.checklist)});await saveProject();closeModal();renderProject('versions')}};$$('[data-openver]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.openver),v=p.goals.versions[i];modal(`<h2>${esc(v.name)}</h2><p class="muted">${new Date(v.at).toLocaleString('ms-MY')}</p><div style="max-height:55dvh;overflow:auto;border:1px solid var(--line);border-radius:12px;padding:14px">${Object.entries(v.content||{}).map(([k,x])=>`<h3>${esc(k)}</h3><div>${x||'<em>Empty</em>'}</div>`).join('')}</div><div class="actions"><button class="btn" onclick="closeModal()">Tutup</button><button class="btn primary" id="restoreVersion">Restore Versi Ini</button></div>`);$('#restoreVersion').onclick=async()=>{p.content=structuredClone(v.content);p.outline=structuredClone(v.outline);p.checklist=structuredClone(v.checklist);await saveProject();closeModal();toast('Versi manuskrip dipulihkan.');renderProject('versions')}});$$('[data-delver]').forEach(b=>b.onclick=async()=>{p.goals.versions.splice(Number(b.dataset.delver),1);await saveProject();renderProject('versions')})}
if(tab==='export'){$('#exportTxt').onclick=()=>downloadBlob(slug(p.title)+'.txt',new Blob([manuscriptText(p)],{type:'text/plain'}));$('#printPdf').onclick=()=>printManuscript(p);$('#exportDocx').onclick=async()=>{const file=await makeDocx(p);downloadBlob(slug(p.title)+'.docx',file)};$('#shareCloud').onclick=async()=>{const file=await makeDocx(p),f=new File([file],slug(p.title)+'.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});if(navigator.canShare?.({files:[f]})){await navigator.share({title:p.title,text:'Naskhah Studio manuscript',files:[f]})}else{downloadBlob(f.name,file);toast('Share sheet tidak disokong. Fail telah dimuat turun.')}}}}
function manuscriptText(p){return Object.entries(p.content).map(([k,v])=>k.toUpperCase()+'\n\n'+stripHtml(v)).join('\n\n\n')}
function slug(s){return String(s||'manuskrip').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'manuskrip'}
function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function printManuscript(p){const w=open('','_blank');w.document.write(`<html><head><title>${esc(p.title)}</title><style>body{font-family:Times New Roman,serif;max-width:800px;margin:40px auto;line-height:1.6}h1{text-align:center}h2{margin-top:32px}img{max-width:100%}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:6px}</style></head><body><h1>${esc(p.title)}</h1>${Object.entries(p.content).map(([k,v])=>`<h2>${esc(k)}</h2>${v}`).join('')}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
async function makeDocx(p){const zip=new JSZip(),xmlEsc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const paras=[];paras.push(`<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:t>${xmlEsc(p.title)}</w:t></w:r></w:p>`);for(const [k,v] of Object.entries(p.content)){paras.push(`<w:p><w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>${xmlEsc(k)}</w:t></w:r></w:p>`);for(const line of stripHtml(v).split(/\n+/).filter(Boolean))paras.push(`<w:p><w:r><w:rPr><w:sz w:val="24"/></w:rPr><w:t xml:space="preserve">${xmlEsc(line)}</w:t></w:r></w:p>`)}zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').file('document.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paras.join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`);return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
async function renderAdmin(){if(state.profile?.role!=='admin')return renderDashboard();nav('admin');const [{data:users,error:uErr},{data:meta,error:mErr}]=await Promise.all([sb.from('nv1_profiles').select('id,username,display_name,email,role,status,plan,subscription_status,subscription_expires_at,created_at,last_seen_at').order('created_at',{ascending:false}),sb.from('nv1_project_metadata').select('*').order('created_at',{ascending:false})]);if(uErr)return toast(uErr.message,true);const us=users||[],ps=mErr?[]:(meta||[]);$('#main').innerHTML=`<div class="page-head"><div><h1>Admin Panel</h1><p>Urus akaun dan langganan. Kandungan manuskrip pengguna tidak dipaparkan.</p></div><button class="btn primary" id="addUser">+ Add User</button></div><div class="stats"><div class="stat"><b>${us.length}</b><span>Registered Users</span></div><div class="stat sections"><b>${us.filter(x=>x.status==='active').length}</b><span>Active Users</span></div><div class="stat words"><b>${ps.length}</b><span>Projects</span></div><div class="stat progress-card"><b>${us.filter(x=>['pro','premium','business'].includes((x.plan||'').toLowerCase())).length}</b><span>Paid Plans</span></div></div><div class="card"><h2>User Management</h2><div class="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Registered</th><th>Plan</th><th>Subscription</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead><tbody>${us.map(u=>`<tr><td><b>${esc(u.display_name||u.username)}</b><br><small>@${esc(u.username)} · ${esc(u.role)}</small></td><td>${esc(u.email||'—')}</td><td>${u.created_at?new Date(u.created_at).toLocaleDateString('ms-MY'):'—'}</td><td>${esc((u.plan||'free').toUpperCase())}</td><td>${esc(u.subscription_status||'trial')}</td><td>${u.subscription_expires_at?new Date(u.subscription_expires_at).toLocaleDateString('ms-MY'):'—'}</td><td>${esc(u.status||'active')}</td><td><button class="btn small edit-user" data-id="${u.id}">Edit</button>${u.role!=='admin'&&u.status!=='active'?` <button class="btn small danger delete-user" data-id="${u.id}">Delete</button>`:''}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><h2>Project Metadata</h2><div class="table-wrap"><table><thead><tr><th>Project</th><th>Type</th><th>User</th><th>Created</th><th>Status</th></tr></thead><tbody>${ps.map(x=>`<tr><td>${esc(x.title||'')}</td><td>${esc(x.project_type||'')}</td><td>${esc(us.find(u=>u.id===x.user_id)?.username||'—')}</td><td>${x.created_at?new Date(x.created_at).toLocaleDateString('ms-MY'):'—'}</td><td>${esc(x.status||'')}</td></tr>`).join('')||'<tr><td colspan="5">Tiada metadata.</td></tr>'}</tbody></table></div></div>`;$('#addUser').onclick=adminCreateDialog;$$('.edit-user').forEach(b=>b.onclick=()=>adminEditDialog(us.find(u=>u.id===b.dataset.id)));$$('.delete-user').forEach(b=>b.onclick=()=>adminDeleteDialog(us.find(u=>u.id===b.dataset.id)))}
function adminCreateDialog(){modal(`<h2>Add User</h2><div class="grid2"><label>Nama<input id="auName"></label><label>Username<input id="auUser"></label></div><label>Email<input id="auEmail" type="email"></label><div class="grid2"><label>Password sementara<input id="auPass" type="password" value="user123"></label><label>Plan<select id="auPlan"><option>free</option><option>pro</option><option>premium</option><option>business</option></select></label></div><div class="grid2"><label>Status Langganan<select id="auSub"><option>trial</option><option>active</option></select></label><label>Tarikh Tamat<input id="auExpiry" type="date"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="createUser">Cipta User</button></div>`);$('#createUser').onclick=async()=>{try{await authCall({action:'admin_create_user',username:$('#auUser').value.trim().toLowerCase(),password:$('#auPass').value,display_name:$('#auName').value.trim(),email:$('#auEmail').value.trim(),plan:$('#auPlan').value,subscription_status:$('#auSub').value,subscription_expires_at:$('#auExpiry').value?new Date($('#auExpiry').value+'T23:59:59').toISOString():null},true);closeModal();toast('User berjaya dicipta.');renderAdmin()}catch(e){toast(e.message,true)}}}
function adminEditDialog(u){const exp=u.subscription_expires_at?new Date(u.subscription_expires_at).toISOString().slice(0,10):'';modal(`<h2>Edit User</h2><div class="grid2"><label>Nama<input id="euName" value="${esc(u.display_name||'')}"></label><label>Username<input value="${esc(u.username||'')}" disabled></label></div><label>Email<input id="euEmail" type="email" value="${esc(u.email||'')}"></label><div class="grid2"><label>Plan<select id="euPlan"><option>free</option><option>pro</option><option>premium</option><option>business</option></select></label><label>Subscription<select id="euSub"><option>trial</option><option>active</option><option>past_due</option><option>cancelled</option><option>expired</option></select></label></div><div class="grid2"><label>Expiry<input id="euExpiry" type="date" value="${exp}"></label><label>Status<select id="euStatus"><option>active</option><option>suspended</option></select></label></div><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="saveUser">Simpan</button></div>`);$('#euPlan').value=u.plan||'free';$('#euSub').value=u.subscription_status||'trial';$('#euStatus').value=u.status||'active';$('#saveUser').onclick=async()=>{const {error}=await sb.from('nv1_profiles').update({display_name:$('#euName').value.trim(),email:$('#euEmail').value.trim()||null,plan:$('#euPlan').value,subscription_status:$('#euSub').value,subscription_expires_at:$('#euExpiry').value?new Date($('#euExpiry').value+'T23:59:59').toISOString():null,status:$('#euStatus').value,updated_at:new Date().toISOString()}).eq('id',u.id);if(error)return toast(error.message,true);closeModal();toast('User dikemas kini.');renderAdmin()}}
function adminDeleteDialog(u){modal(`<h2>Delete User</h2><p>Akaun <b>${esc(u.username)}</b> akan dipadam. Fungsi ini hanya dipaparkan untuk user yang tidak aktif/suspended.</p><label>Taip DELETE<input id="delConfirm"></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn danger" id="confirmDelete">Delete User</button></div>`);$('#confirmDelete').onclick=async()=>{if($('#delConfirm').value!=='DELETE')return toast('Taip DELETE untuk sahkan.',true);try{await authCall({action:'admin_delete_user',user_id:u.id},true);closeModal();toast('User dipadam.');renderAdmin()}catch(e){toast(e.message,true)}}}
function bindAuth(){$('#goAdmin').onclick=()=>showPublic('admin');$$('.toLogin').forEach(x=>x.onclick=()=>showPublic('login'));$('#forgotLink').onclick=()=>showPublic('forgot');$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const j=await authCall({action:'login',identifier:$('#loginUser').value.trim(),password:$('#loginPass').value});await setSession(j.access_token,j.refresh_token);if(state.profile?.status==='suspended')throw new Error('Akaun digantung. Hubungi admin.');await enterApp()}catch(err){toast(err.message,true)}};$('#adminForm').onsubmit=async e=>{e.preventDefault();try{const j=await authCall({action:'login',identifier:$('#adminUser').value.trim(),password:$('#adminPass').value});await setSession(j.access_token,j.refresh_token);if(state.profile?.role!=='admin'){await sb.auth.signOut();throw new Error('Akaun ini bukan admin.')}await enterApp()}catch(err){toast(err.message,true)}};$('#forgotForm').onsubmit=async e=>{e.preventDefault();try{await authCall({action:'forgot',identifier:$('#forgotUser').value.trim(),redirect_to:location.origin+location.pathname});toast('Jika email recovery wujud, reset link telah dihantar.');showPublic('login')}catch(err){toast(err.message,true)}};$('#resetForm').onsubmit=async e=>{e.preventDefault();const a=$('#resetPass').value,b=$('#resetPass2').value;if(a!==b)return toast('Password tidak sama.',true);const {error}=await sb.auth.updateUser({password:a});if(error)return toast(error.message,true);toast('Password berjaya ditukar.');showPublic('login')}}
async function boot(){bindGlobal();bindAuth();const {data:{session}}=await sb.auth.getSession();if(session){try{state.session=session;await loadProfile();if(state.profile?.status==='active')return enterApp()}catch{}await sb.auth.signOut()}showPublic('login')}
document.addEventListener('DOMContentLoaded',boot);