const {createClient}=supabase;
const SUPABASE_URL='https://nrnrmbjrczmzkgimxdun.supabase.co';
const SUPABASE_KEY='sb_publishable_Lrb0SZIai9FwSYy0oDbnzg_vZ4BTakA';
const AUTH_URL=SUPABASE_URL+'/functions/v1/naskhah-v1-auth';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stripHtml=s=>{const d=document.createElement('div');d.innerHTML=String(s||'');return d.textContent||d.innerText||''};
const countWords=s=>{const t=stripHtml(s).trim();return t?t.split(/\s+/).length:0};
const reminderOptions=v=>Array.from({length:30},(_,i)=>`<option value="${i+1}" ${Number(v||7)===i+1?'selected':''}>${i+1} hari sebelum</option>`).join('');
const templates={
 article:{label:'Artikel Jurnal',target:10000,sections:['Abstract','Keywords','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion','Acknowledgement','References'],phases:[['Persediaan Kajian',['Tentukan topik','Research problem','Research gap','Research questions','Objectives','Target journal']],['Rangka Artikel',['Title','Abstract','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion']],['Research & Sources',['Collect references','Review papers','Save DOI','Organize citations','Figures / tables']],['Menulis',['Abstract','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion']],['Academic Editing',['Grammar','Academic tone','Argument flow','Citation check','Similarity check','Word count']],['Review',['Co-author review','Supervisor review','Peer feedback','Revision']],['Submission',['Journal formatting','Cover letter','Author details','References','Submission checklist','Submit','Revision tracking']]]},
 thesis:{label:'Tesis',target:70000,sections:['Abstract','Acknowledgement','Chapter 1: Introduction','Chapter 2: Literature Review','Chapter 3: Methodology','Chapter 4: Results / Findings','Chapter 5: Discussion','Chapter 6: Conclusion & Recommendations','References','Appendices'],phases:[['Persediaan',['Tentukan topik','Research problem','Research gap','Research questions','Objectives','Scope','Supervisor discussion']],['Rangka Tesis',['Abstract','Introduction','Literature Review','Methodology','Results / Findings','Discussion','Conclusion & Recommendations']],['Research & Data',['Ethics approval jika perlu','Data collection','Reference management','Figures / tables','Data analysis plan']],['Menulis',['Chapter 1','Chapter 2','Chapter 3','Chapter 4','Chapter 5','Chapter 6']],['Suntingan Akademik',['Academic tone','Argument flow','Citation check','Formatting','Tables / figures','Word count']],['Semakan Penyelia',['Submit chapters','Receive feedback','Revision','Supervisor approval']],['Akhir & Submission',['Final proofreading','University formatting','Declaration / front matter','References','Appendices','Final thesis submission']]]},
 book:{label:'Buku',target:50000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Penutup'],phases:[['Persediaan',['Tentukan tujuan buku','Pembaca sasaran','Genre','Gaya penulisan','Target words','Deadline']],['Rangka Buku',['Tajuk','Bahagian','Bab','Subbab','Susun flow buku']],['Jadual',['Tarikh mula','Tarikh siap','Daily writing goal','Weekly writing target','Jadual bab']],['Menulis',['Tulis bab demi bab','Semak target words','Lengkapkan manuskrip']],['Suntingan',['Self edit','Grammar','Structure','Consistency','Fact checking']],['Maklum Balas',['Beta reader','Editor','Peer review','Feedback','Revision']],['Akhir',['Final proofread','Formatting','Cover','ISBN','Export','Publish']]]},
 ebook:{label:'eBook',target:15000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Checklist / Bonus','Penutup','CTA'],phases:[['Idea & Audience',['Tentukan masalah pembaca','Persona pembaca','Outcome eBook']],['Outline',['Tajuk','Bab','Subbab','Flow']],['Content Plan',['Research','Contoh','Visual','Jadual penulisan']],['Writing',['Draft setiap bab','Lengkapkan CTA','Semak target']],['Editing',['Bahasa','Flow','Kejelasan','Fact check']],['Design & Review',['Layout','Cover','Visual','Proofread','Feedback']],['Publishing',['Final PDF','EPUB','Landing copy','Publish']]]}
};
let state=window.NaskhahCore.createState();
let authCall,setSession,loadProfile,loadProjects;
let writingView,bindWriter,openTableDialog,uploadImage,hydrateImages;
let overviewView,deadlinesView,specialSubmissionView,outlineView,checklistView,notesView,referencesView,exportView;
let projectCard,renderDashboard,reminderCentre,renderProjects,openCreate,createProject,normalizeProject,openProject;
let renderProfile,bindGlobal;
let projectWords,projectPct,tabs,renderProject;
let saveProject;
let bindTab;
let renderAdmin,adminCreateDialog,adminEditDialog,adminDeleteDialog;
let bindAuth,boot;
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(bad?' bad':'');clearTimeout(t._x);t._x=setTimeout(()=>t.className='toast',2600)}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');$('#modalContent').innerHTML=''}
window.closeModal=closeModal;
function showPublic(panel='login'){$('#public').classList.remove('hidden');$('#app').classList.add('hidden');$$('.auth-panel').forEach(x=>x.classList.add('hidden'));$('#'+panel+'Panel').classList.remove('hidden')}
async function enterApp(){await loadProjects();$('#public').classList.add('hidden');$('#app').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',state.profile?.role!=='admin');renderDashboard()}
function nav(name){$$('.sidebar [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(innerWidth<=820)toggleNav(false)}
function toggleNav(force){const app=$('#app'),on=force??!app.classList.contains('nav-open');app.classList.toggle('nav-open',on)}
function versionsView(p){const arr=p.goals.versions||[];return `<div class="card"><div class="card-head"><div><h2>Versions</h2><p class="muted">Simpan manuskrip secara manual dan buka semula bila diperlukan.</p></div><button class="btn primary" id="saveVersion">Simpan Manuskrip</button></div>${arr.length?arr.slice().reverse().map((v,ri)=>{const i=arr.length-1-ri;return `<div class="version-row"><div><b>${esc(v.name)}</b><div class="muted">${new Date(v.at).toLocaleString('ms-MY')}</div></div><div class="actions"><button class="btn small" data-openver="${i}">Buka</button><button class="btn small danger" data-delver="${i}">Delete</button></div></div>`}).join(''):'<p class="muted">Belum ada manuskrip disimpan.</p>'}</div>`}
function manuscriptText(p){return Object.entries(p.content).map(([k,v])=>k.toUpperCase()+'\n\n'+stripHtml(v)).join('\n\n\n')}
function slug(s){return String(s||'manuskrip').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'manuskrip'}
function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function printManuscript(p){const w=open('','_blank');w.document.write(`<html><head><title>${esc(p.title)}</title><style>body{font-family:Times New Roman,serif;max-width:800px;margin:40px auto;line-height:1.6}h1{text-align:center}h2{margin-top:32px}img{max-width:100%}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:6px}</style></head><body><h1>${esc(p.title)}</h1>${Object.entries(p.content).map(([k,v])=>`<h2>${esc(k)}</h2>${v}`).join('')}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
async function makeDocx(p){const zip=new JSZip(),xmlEsc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const paras=[];paras.push(`<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:t>${xmlEsc(p.title)}</w:t></w:r></w:p>`);for(const [k,v] of Object.entries(p.content)){paras.push(`<w:p><w:r><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:t>${xmlEsc(k)}</w:t></w:r></w:p>`);for(const line of stripHtml(v).split(/\n+/).filter(Boolean))paras.push(`<w:p><w:r><w:rPr><w:sz w:val="24"/></w:rPr><w:t xml:space="preserve">${xmlEsc(line)}</w:t></w:r></w:p>`)}zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').file('document.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paras.join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`);return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}