const {createClient}=supabase;
const SUPABASE_URL='https://nrnrmbjrczmzkgimxdun.supabase.co';
const SUPABASE_KEY='sb_publishable_Lrb0SZIai9FwSYy0oDbnzg_vZ4BTakA';
const AUTH_URL=SUPABASE_URL+'/functions/v1/naskhah-v1-auth';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const countWords=s=>String(s||'').trim()?String(s).trim().split(/\s+/).length:0;
const templates={
 article:{label:'Artikel Jurnal',target:7000,sections:['Abstract','Keywords','Introduction','Literature Review','Methodology','Results','Discussion','Conclusion','References'],phases:[['Persediaan Kajian',['Tentukan topik','Research problem','Research gap','Research question','Objective','Target journal']],['Rangka Artikel',['Title','Abstract','Introduction','Literature Review','Methodology','Results','Discussion','Conclusion']],['Research & Sources',['Collect references','Review papers','Save DOI','Organize citations','Figures / tables']],['Menulis',['Abstract','Introduction','Literature Review','Methodology','Results','Discussion','Conclusion']],['Academic Editing',['Grammar','Academic tone','Argument flow','Citation check','Similarity check','Word count']],['Review',['Co-author review','Supervisor review','Peer feedback','Revision']],['Submission',['Journal formatting','Cover letter','Author details','References','Submission checklist','Submit','Revision tracking']]]},
 book:{label:'Buku',target:50000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Penutup'],phases:[['Persediaan',['Tentukan tujuan buku','Pembaca sasaran','Genre','Gaya penulisan','Target words','Deadline']],['Rangka Buku',['Tajuk','Bahagian','Bab','Subbab','Susun flow buku']],['Jadual Penulisan',['Tarikh mula','Tarikh siap','Daily writing goal','Weekly writing target','Jadual bab']],['Menulis',['Tulis bab demi bab','Semak target words','Lengkapkan manuskrip']],['Suntingan',['Self edit','Grammar','Structure','Consistency','Fact checking']],['Maklum Balas',['Beta reader','Editor','Peer review','Feedback','Revision']],['Akhir',['Final proofread','Formatting','Cover','ISBN','Export','Publish']]]},
 ebook:{label:'eBook',target:15000,sections:['Pengenalan','Bab 1','Bab 2','Bab 3','Checklist / Bonus','Penutup','CTA'],phases:[['Idea & Audience',['Tentukan masalah pembaca','Persona pembaca','Outcome eBook']],['Outline',['Tajuk','Bab','Subbab','Flow']],['Content Plan',['Research','Contoh','Visual','Jadual penulisan']],['Writing',['Draft setiap bab','Lengkapkan CTA','Semak target']],['Editing',['Bahasa','Flow','Kejelasan','Fact check']],['Design & Review',['Layout','Cover','Visual','Proofread','Feedback']],['Publishing',['Final PDF','EPUB','Landing copy','Publish']]]}
};
let state={session:null,profile:null,projects:[],current:null,view:'dashboard'};
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className='toast show '+(bad?'bad':'');setTimeout(()=>t.className='toast',2600)}
async function authCall(payload){const r=await fetch(AUTH_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ralat');return j}
async function setSession(a,r){const {data,error}=await sb.auth.setSession({access_token:a,refresh_token:r});if(error)throw error;state.session=data.session;await loadProfile();}
async function loadProfile(){const u=(await sb.auth.getUser()).data.user;if(!u)return;const {data}=await sb.from('nv1_profiles').select('*').eq('id',u.id).single();state.profile=data;}
async function loadProjects(){if(!state.session)return;const {data,error}=await sb.from('nv1_projects').select('*').order('updated_at',{ascending:false});if(error)throw error;state.projects=data||[];}
function showPublic(panel='login'){state.session=null;state.profile=null;state.current=null;$('#public').classList.remove('hidden');$('#app').classList.add('hidden');$$('.auth-panel').forEach(x=>x.classList.add('hidden'));$('#'+panel+'Panel').classList.remove('hidden');}
async function enterApp(){await loadProjects();$('#public').classList.add('hidden');$('#app').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',state.profile?.role!=='admin');renderDashboard();}
function renderDashboard(){state.view='dashboard';state.current=null;setActiveNav('dashboard');const words=state.projects.reduce((n,p)=>n+projectWords(p),0),completed=state.projects.filter(p=>p.status==='complete').length;$('#main').innerHTML=`<div class="page-head"><div><h1>Dashboard</h1><p>Selamat datang, ${escapeHtml(state.profile?.display_name||state.profile?.username||'Penulis')}.</p></div><button class="btn primary" id="newProject">+ Projek Baharu</button></div><div class="stats"><div class="stat"><b>${state.projects.length}</b><span>Projek</span></div><div class="stat"><b>${words.toLocaleString()}</b><span>Perkataan</span></div><div class="stat"><b>${completed}</b><span>Selesai</span></div><div class="stat"><b>${state.projects.filter(p=>p.status!=='complete').length}</b><span>Aktif</span></div></div><div class="card"><div class="card-head"><h2>Projek Terkini</h2></div><div class="project-grid">${state.projects.length?state.projects.map(projectCard).join(''):'<div class="empty">Belum ada projek. Cipta projek pertama anda.</div>'}</div></div>`;$('#newProject').onclick=openCreate;$$('[data-open]').forEach(b=>b.onclick=()=>openProject(b.dataset.open));}
function projectWords(p){return Object.values(p.content||{}).reduce((n,v)=>n+countWords(v),0)}
function projectCard(p){const w=projectWords(p),pct=Math.min(100,Math.round((w/Math.max(1,p.target_words||1))*100));return `<button class="project-card" data-open="${p.id}"><div class="type-pill">${escapeHtml(templates[p.project_type]?.label||p.project_type)}</div><h3>${escapeHtml(p.title)}</h3><div class="progress"><i style="width:${pct}%"></i></div><div class="muted">${w.toLocaleString()} / ${(p.target_words||0).toLocaleString()} perkataan · ${pct}%</div></button>`}
function openCreate(){const opts=Object.entries(templates).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');modal(`<h2>Projek Baharu</h2><label>Tajuk<input id="cpTitle" placeholder="Tajuk penulisan"></label><label>Jenis<select id="cpType">${opts}</select></label><label>Target perkataan<input id="cpTarget" type="number" value="7000"></label><label>Deadline<input id="cpDeadline" type="date"></label><label>Bahasa<select id="cpLang"><option>Malay</option><option>English</option></select></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="cpSave">Cipta Projek</button></div>`);$('#cpType').onchange=e=>$('#cpTarget').value=templates[e.target.value].target;$('#cpSave').onclick=createProject;}
async function createProject(){const type=$('#cpType').value,title=$('#cpTitle').value.trim();if(!title)return toast('Masukkan tajuk.',true);const t=templates[type],content=Object.fromEntries(t.sections.map(s=>[s,''])),outline=t.sections.filter(s=>!['Keywords','References'].includes(s)).map((s,i)=>({id:crypto.randomUUID(),title:s,notes:'',target_words:Math.round(Number($('#cpTarget').value||t.target)/Math.max(1,t.sections.length)),status:'not_started',children:[],order:i})),checklist=t.phases.map(([name,items],i)=>({id:crypto.randomUUID(),name,order:i,items:items.map(x=>({id:crypto.randomUUID(),text:x,done:false}))}));const u=(await sb.auth.getUser()).data.user;const {data,error}=await sb.from('nv1_projects').insert({user_id:u.id,title,project_type:type,target_words:Number($('#cpTarget').value||t.target),deadline:$('#cpDeadline').value||null,language:$('#cpLang').value,status:'draft',content,outline,checklist,goals:{daily:500,weekly:3000}}).select().single();if(error)return toast(error.message,true);closeModal();state.projects.unshift(data);openProject(data.id);}
function openProject(id){state.current=state.projects.find(p=>p.id===id);if(!state.current)return;renderProject('overview')}
function projectTabs(active){return `<div class="tabs">${[['overview','Overview'],['writing','Zon Menulis'],['outline','Pengurus Rangka'],['checklist','Senarai Semak'],['notes','Research Notes'],['references','References'],['versions','Versions'],['export','Export']].map(([k,l])=>`<button data-ptab="${k}" class="${active===k?'active':''}">${l}</button>`).join('')}</div>`}
function bindProjectTabs(){$$('[data-ptab]').forEach(x=>x.onclick=()=>renderProject(x.dataset.ptab))}