async function boot(){const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('type')==='recovery'||location.hash.includes('access_token=')){$('#public').classList.remove('hidden');$$('.auth-panel').forEach(x=>x.classList.add('hidden'));$('#resetPanel').classList.remove('hidden');return}const {data}=await sb.auth.getSession();if(data.session){state.session=data.session;await loadProfile();if(state.profile) return enterApp()}showPublic('login')}
window.addEventListener('DOMContentLoaded',()=>{
 $('#goLogin').onclick=()=>showPublic('login');$('#goRegister').onclick=()=>showPublic('register');$('#goAdmin').onclick=()=>showPublic('admin');$('#forgotLink').onclick=()=>showPublic('forgot');$$('.toLogin').forEach(x=>x.onclick=()=>showPublic('login'));
 $('#loginForm').onsubmit=async e=>{e.preventDefault();try{const j=await authCall({action:'login',username:$('#loginUser').value,password:$('#loginPass').value});await setSession(j.access_token,j.refresh_token);enterApp()}catch(err){toast(err.message,true)}};
 $('#adminForm').onsubmit=async e=>{e.preventDefault();try{const j=await authCall({action:'login',username:$('#adminUser').value,password:$('#adminPass').value});await setSession(j.access_token,j.refresh_token);if(state.profile.role!=='admin'){await sb.auth.signOut();return toast('Akaun ini bukan admin.',true)}enterApp()}catch(err){toast(err.message,true)}};
 $('#registerForm').onsubmit=async e=>{e.preventDefault();if($('#regPass').value!==$('#regPass2').value)return toast('Password tidak sepadan.',true);try{await authCall({action:'register',display_name:$('#regName').value,username:$('#regUser').value,password:$('#regPass').value,email:$('#regEmail').value});toast('Pendaftaran berjaya. Sila login.');setTimeout(()=>showPublic('login'),700)}catch(err){toast(err.message,true)}};
 $('#forgotForm').onsubmit=async e=>{e.preventDefault();try{await authCall({action:'forgot',username:$('#forgotUser').value,redirect_to:location.origin});toast('Link reset dihantar ke email recovery.')}catch(err){toast(err.message,true)}};
 $('#resetForm').onsubmit=async e=>{e.preventDefault();if($('#resetPass').value!==$('#resetPass2').value)return toast('Password tidak sepadan.',true);const {error}=await sb.auth.updateUser({password:$('#resetPass').value});if(error)return toast(error.message,true);toast('Password berjaya ditukar.');history.replaceState(null,'',location.pathname);await sb.auth.signOut();setTimeout(()=>showPublic('login'),700)};
 $$('[data-nav]').forEach(n=>n.onclick=()=>{const k=n.dataset.nav;if(k==='dashboard')renderDashboard();if(k==='projects')renderProjects();if(k==='admin')renderAdmin();if(k==='profile')renderProfile()});$('#logout').onclick=async()=>{await sb.auth.signOut();showPublic('login')};boot();
});