// Smart Deadline Planner — Journal Article
const _baseOpenCreate=openCreate,_baseRenderDashboard=renderDashboard,_baseRenderProject=renderProject,_baseProjectCard=projectCard,_baseSaveProject=saveProject;
function dateOnly(d){if(!d)return null;const x=new Date(d+'T12:00:00');return isNaN(x)?null:x}
function addDays(date,n){const d=new Date(date);d.setDate(d.getDate()+n);return d}
function daysBetween(a,b){return Math.ceil((b-a)/86400000)}
function fmtDate(d){return d?new Date(d).toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function buildJournalPlan(submission){const d=dateOnly(submission);if(!d)return[];const defs=[
 {offset:-42,phase:'Fasa 1',title:'Persediaan kajian & skop',target:8,detail:'Topik, masalah, research gap, objective dan target journal.'},
 {offset:-28,phase:'Fasa 2',title:'Rangka artikel lengkap',target:18,detail:'Struktur Title hingga Conclusion telah dirancang.'},
 {offset:-14,phase:'Fasa 3–4',title:'Full first draft',target:75,detail:'Research, references dan manuskrip pertama telah lengkap.'},
 {offset:-7,phase:'Fasa 5',title:'Academic editing',target:88,detail:'Bahasa akademik, flow, citation dan word count disemak.'},
 {offset:-3,phase:'Fasa 6',title:'Review & revision',target:95,detail:'Maklum balas co-author/supervisor dimasukkan.'},
 {offset:-1,phase:'Fasa 7',title:'Submission ready',target:100,detail:'Formatting, cover letter dan checklist submission siap.'},
 {offset:0,phase:'D-Day',title:'Submit article',target:100,detail:'Hantar artikel sebelum deadline rasmi.'}
 ];return defs.map((x,i)=>({...x,id:'deadline-'+i,date:addDays(d,x.offset).toISOString().slice(0,10)}))}
function deadlineInfo(p){const due=dateOnly(p.submission_date||p.deadline);if(!due)return{status:'not_set',label:'Tiada deadline',days:null,className:''};const today=new Date();today.setHours(12,0,0,0);const days=daysBetween(today,due),progress=Math.min(100,Math.round(projectWords(p)/Math.max(1,p.target_words)*100));let status='on_track',label='On Track';if(days<0){status='overdue';label='Overdue'}else if(days===0){status='due_today';label='Due Today'}else{const plan=buildJournalPlan(due.toISOString().slice(0,10));const passed=plan.filter(m=>dateOnly(m.date)<=today);const expected=passed.length?passed[passed.length-1].target:0;if(progress+20<expected){status='behind';label='Behind Schedule'}else if(progress+8<expected||days<=3){status='at_risk';label='At Risk'}}return{status,label,days,className:status}}
function nextMilestone(p){const due=p.submission_date||p.deadline;if(!due)return null;const today=new Date();today.setHours(0,0,0,0);return buildJournalPlan(due).find(m=>dateOnly(m.date)>=today)||buildJournalPlan(due).slice(-1)[0]}
function reminderText(p){const info=deadlineInfo(p);if(info.days===null)return'';if(info.days<0)return`${Math.abs(info.days)} hari lewat`;if(info.days===0)return'Due hari ini';return`${info.days} hari lagi`}
openCreate=function(){const opts=Object.entries(templates).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');modal(`<h2>Projek Baharu</h2><label>Tajuk<input id="cpTitle" placeholder="Tajuk penulisan"></label><label>Jenis<select id="cpType">${opts}</select></label><label>Target perkataan<input id="cpTarget" type="number" value="7000"></label><div id="deadlineFields"><label>Target Submission / Due Date<input id="cpDeadline" type="date"></label><label id="deadlineTypeWrap">Jenis Deadline<select id="cpDeadlineType"><option value="journal_submission">Journal Submission</option><option value="special_issue">Special Issue</option><option value="conference">Conference Paper</option><option value="revision">Revision Deadline</option><option value="camera_ready">Camera-ready / Final Manuscript</option><option value="custom">Custom</option></select></label></div><label>Bahasa<select id="cpLang"><option>Malay</option><option>English</option></select></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="cpSave">Cipta Projek</button></div>`);const type=$('#cpType');const sync=()=>{$('#cpTarget').value=templates[type.value].target;$('#deadlineTypeWrap').style.display=type.value==='article'?'block':'none'};type.onchange=sync;sync();$('#cpSave').onclick=createProjectSmart;}
async function createProjectSmart(){const type=$('#cpType').value,title=$('#cpTitle').value.trim();if(!title)return toast('Masukkan tajuk.',true);const t=templates[type],target=Number($('#cpTarget').value||t.target),due=$('#cpDeadline').value||null,content=Object.fromEntries(t.sections.map(s=>[s,''])),outline=t.sections.filter(s=>!['Keywords','References'].includes(s)).map((s,i)=>({id:crypto.randomUUID(),title:s,notes:'',target_words:Math.round(target/Math.max(1,t.sections.length)),status:'not_started',children:[],order:i})),checklist=t.phases.map(([name,items],i)=>({id:crypto.randomUUID(),name,order:i,items:items.map(x=>({id:crypto.randomUUID(),text:x,done:false}))}));const u=(await sb.auth.getUser()).data.user;const plan=type==='article'&&due?buildJournalPlan(due):[];const payload={user_id:u.id,title,project_type:type,target_words:target,deadline:due,submission_date:type==='article'?due:null,deadline_type:type==='article'?$('#cpDeadlineType').value:'custom',deadline_plan:plan,deadline_status:due?'on_track':'not_set',reminder_offsets:[7,3,1,0],language:$('#cpLang').value,status:'draft',content,outline,checklist,goals:{daily:500,weekly:3000}};const {data,error}=await sb.from('nv1_projects').insert(payload).select().single();if(error)return toast(error.message,true);closeModal();state.projects.unshift(data);openProject(data.id)}
projectCard=function(p){const base=_baseProjectCard(p);if(!p.deadline)return base;const info=deadlineInfo(p);return base.replace('</button>',`<div class="deadline-mini ${info.className}"><b>${escapeHtml(info.label)}</b><span>${escapeHtml(reminderText(p))}</span></div></button>`)};
renderDashboard=function(){_baseRenderDashboard();const upcoming=state.projects.filter(p=>p.deadline&&p.status!=='complete').sort((a,b)=>String(a.deadline).localeCompare(String(b.deadline))).slice(0,5);if(!upcoming.length)return;const main=$('#main'),cards=upcoming.map(p=>{const info=deadlineInfo(p),m=p.project_type==='article'?nextMilestone(p):null;return `<button class="deadline-row" data-open="${p.id}"><div><b>${escapeHtml(p.title)}</b><span>${escapeHtml(templates[p.project_type]?.label||p.project_type)} · ${m?escapeHtml(m.title):'Project deadline'}</span></div><div class="deadline-right"><strong class="deadline-badge ${info.className}">${escapeHtml(info.label)}</strong><span>${escapeHtml(reminderText(p))}</span><small>${fmtDate(p.deadline)}</small></div></button>`}).join('');main.insertAdjacentHTML('beforeend',`<div class="card deadline-card"><div class="card-head"><div><h2>Upcoming Deadlines</h2><p>Reminder berdasarkan due date projek anda.</p></div></div>${cards}</div>`);$$('[data-open]').forEach(b=>b.onclick=()=>openProject(b.dataset.open));}
renderProject=function(tab){_baseRenderProject(tab);const p=state.current;if(!p||tab!=='overview'||p.project_type!=='article')return;const due=p.submission_date||p.deadline;if(!due)return;const info=deadlineInfo(p),plan=buildJournalPlan(due),today=new Date();today.setHours(12,0,0,0),next=nextMilestone(p);const html=`<div class="card smart-deadline"><div class="card-head"><div><h2>Smart Deadline Planner</h2><p>${escapeHtml(p.deadline_type||'journal_submission').replaceAll('_',' ')} · Submission ${fmtDate(due)}</p></div><div class="deadline-badge ${info.className}">${escapeHtml(info.label)}</div></div><div class="deadline-summary"><div><b>${info.days<0?Math.abs(info.days):info.days}</b><span>${info.days<0?'hari overdue':info.days===0?'due hari ini':'hari lagi'}</span></div><div><b>${next?fmtDate(next.date):'—'}</b><span>Milestone seterusnya</span></div><div><b>${next?next.target+'%':'100%'}</b><span>Expected progress</span></div></div><div class="timeline">${plan.map(m=>{const done=dateOnly(m.date)<today,active=next&&m.id===next.id;return `<div class="timeline-item ${done?'passed':''} ${active?'active':''}"><i></i><div><small>${m.phase} · ${fmtDate(m.date)}</small><b>${escapeHtml(m.title)}</b><p>${escapeHtml(m.detail)}</p><span>Target progress: ${m.target}%</span></div></div>`}).join('')}</div><div class="reminder-note"><b>Reminder:</b> sistem menandakan deadline pada 7 hari, 3 hari, 1 hari dan hari submission. Status berubah kepada At Risk / Behind Schedule berdasarkan kemajuan manuskrip.</div></div>`;const tabs=$('.tabs');if(tabs)tabs.insertAdjacentHTML('afterend',html);}
saveProject=async function(){const p=state.current;p.updated_at=new Date().toISOString();if(p.project_type==='article'&&p.deadline){p.submission_date=p.deadline;p.deadline_plan=buildJournalPlan(p.deadline);p.deadline_status=deadlineInfo(p).status}const {error}=await sb.from('nv1_projects').update({title:p.title,target_words:p.target_words,deadline:p.deadline,submission_date:p.submission_date||null,deadline_type:p.deadline_type||'custom',deadline_plan:p.deadline_plan||[],deadline_status:p.deadline_status||'not_set',reminder_offsets:p.reminder_offsets||[7,3,1,0],status:p.status,content:p.content,outline:p.outline,checklist:p.checklist,goals:p.goals,updated_at:p.updated_at}).eq('id',p.id);if(error)toast(error.message,true)};
