// V1.3 — Academic article structure, section word detector & DOCX export
(function(){
  // Research article default: literature/background before methodology.
  if(templates.article){
    templates.article.target=8000;
    templates.article.sections=['Abstract','Keywords','Introduction','Literature Review','Methodology','Results and Discussion','Conclusion','Acknowledgement','References'];
  }
  function plainText(html){const d=document.createElement('div');d.innerHTML=String(html||'');return d.innerText||d.textContent||''}
  function sectionTarget(name,total){const map={'Abstract':250,'Keywords':50,'Introduction':Math.round(total*.15),'Literature Review':Math.round(total*.20),'Methodology':Math.round(total*.15),'Results and Discussion':Math.round(total*.35),'Conclusion':Math.round(total*.10),'Acknowledgement':150,'References':0};return map[name]??Math.round(total/7)}
  const oldHealth=healthRows;
  healthRows=function(p){const total=p.target_words||8000;return Object.entries(p.content||{}).map(([k,v])=>{const n=countWords(plainText(v)),target=sectionTarget(k,total),pct=target?Math.min(100,Math.round(n/target*100)):0,s=n===0?'Belum mula':target&&n>=target?'Target dicapai':n<100?'Draft awal':'Sedang ditulis';return `<div class="health"><span>${escapeHtml(k)}</span><b>${n.toLocaleString()} words${target?' / '+target.toLocaleString():''}</b><em>${s}${target?' · '+pct+'%':''}</em></div>`}).join('')};
  const oldExport=exportView;
  exportView=function(){return `<div class="grid2"><div class="card"><h2>Export Manuskrip</h2><p>Gabungkan semua bahagian manuskrip mengikut struktur projek.</p><button class="btn primary" id="exportDocx">Download Word (.docx)</button> <button class="btn" id="exportTxt">Export TXT</button> <button class="btn" id="printPdf">Print / Save PDF</button><p class="muted">Word export mengekalkan tajuk bahagian dan basic rich-text formatting.</p></div><div class="card"><h2>Word Detector</h2>${healthRows(state.current)}</div></div>`};
  const oldBind=bindTab;
  bindTab=function(tab){oldBind(tab);if(tab!=='export')return;const p=state.current,btn=$('#exportDocx');if(btn)btn.onclick=()=>downloadDocx(p)};
  function xmlEscape(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
  function paragraph(text,bold=false){return `<w:p><w:r>${bold?'<w:rPr><w:b/></w:rPr>':''}<w:t xml:space="preserve">${xmlEscape(text)}</w:t></w:r></w:p>`}
  async function downloadDocx(p){try{if(typeof JSZip==='undefined')throw new Error('DOCX library belum dimuatkan. Refresh halaman dan cuba semula.');let body=paragraph(p.title,true);Object.entries(p.content||{}).forEach(([k,v])=>{body+=paragraph(k,true);plainText(v).split(/\n+/).filter(Boolean).forEach(x=>body+=paragraph(x))});const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;const zip=new JSZip();zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').file('document.xml',doc);const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=p.title.replace(/[^a-z0-9]+/gi,'-')+'.docx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,true)}}
})();