// V1.4 — Manuscript Version Manager
const _v14VersionView=versionView;
const _v14BindTab=bindTab;
function manuscriptVersions(p){p.goals=p.goals||{};p.goals.versions=Array.isArray(p.goals.versions)?p.goals.versions:[];return p.goals.versions}
function versionWords(v){return Object.values(v.content||{}).reduce((n,x)=>n+sectionWordCount(x),0)}
versionView=function(){const p=state.current,arr=manuscriptVersions(p);const rows=arr.length?arr.map((v,i)=>({...v,_i:i})).reverse().map(v=>`<div class="manuscript-version-row"><div class="mv-main"><b>${escapeHtml(v.name||('Manuskrip '+(v._i+1)))}</b><span>${new Date(v.at).toLocaleString('ms-MY')} · ${versionWords(v).toLocaleString()} perkataan</span>${v.note?`<p>${escapeHtml(v.note)}</p>`:''}</div><div class="mv-actions"><button class="btn mv-open" data-vi="${v._i}">Buka</button><button class="btn mv-restore" data-vi="${v._i}">Pulihkan</button><button class="btn danger-soft mv-delete" data-vi="${v._i}">Padam</button></div></div>`).join(''):'<div class="empty">Belum ada manuskrip disimpan. Autosave tetap aktif semasa anda menulis.</div>';return `<div class="card"><div class="card-head"><div><h2>Versi Manuskrip</h2><p>Simpan checkpoint manuskrip tanpa mengganggu autosave semasa.</p></div><button class="btn primary" id="saveManuscript">Simpan Manuskrip</button></div>${rows}</div>`};
function openManuscriptPreview(v){const sections=Object.entries(v.content||{}).map(([k,val])=>`<section class="mv-preview-section"><h3>${escapeHtml(k)}</h3><div>${val||'<em>Belum ditulis</em>'}</div></section>`).join('');modal(`<div class="mv-preview-head"><div><h2>${escapeHtml(v.name||'Versi Manuskrip')}</h2><p>${new Date(v.at).toLocaleString('ms-MY')} · ${versionWords(v).toLocaleString()} perkataan</p></div></div>${v.note?`<div class="mv-note"><b>Catatan:</b> ${escapeHtml(v.note)}</div>`:''}<div class="mv-preview">${sections}</div><div class="actions"><button class="btn" onclick="closeModal()">Tutup</button></div>`)}
function saveManuscriptDialog(p){const next=manuscriptVersions(p).length+1;modal(`<h2>Simpan Manuskrip</h2><p>Simpan satu versi manuskrip untuk rujukan atau pemulihan kemudian.</p><label>Nama versi<input id="mvName" value="Manuskrip ${next}" placeholder="Contoh: Draft sebelum semakan penyelia"></label><label>Catatan <small>(optional)</small><textarea id="mvNote" placeholder="Contoh: Versi sebelum pembetulan metodologi"></textarea></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="mvConfirm">Simpan Manuskrip</button></div>`);$('#mvConfirm').onclick=async()=>{const name=$('#mvName').value.trim()||`Manuskrip ${next}`,note=$('#mvNote').value.trim();manuscriptVersions(p).push({id:crypto.randomUUID(),name,note,at:new Date().toISOString(),content:structuredClone(p.content||{}),outline:structuredClone(p.outline||[]),checklist:structuredClone(p.checklist||[]),target_words:p.target_words,deadline:p.deadline,submission_date:p.submission_date||null});await saveProject();closeModal();toast('Manuskrip berjaya disimpan.');renderProject('versions')}}
bindTab=function(tab){if(tab!=='versions')return _v14BindTab(tab);const p=state.current,arr=manuscriptVersions(p);$('#saveManuscript').onclick=()=>saveManuscriptDialog(p);$$('.mv-open').forEach(b=>b.onclick=()=>openManuscriptPreview(arr[Number(b.dataset.vi)]));$$('.mv-restore').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.vi),v=arr[i];if(!v)return;if(!confirm(`Pulihkan "${v.name}"? Manuskrip semasa akan digantikan.`))return;p.content=structuredClone(v.content||{});p.outline=structuredClone(v.outline||[]);p.checklist=structuredClone(v.checklist||[]);if(v.target_words)p.target_words=v.target_words;if(v.deadline)p.deadline=v.deadline;if(v.submission_date)p.submission_date=v.submission_date;await saveProject();toast('Versi manuskrip dipulihkan.');renderProject('versions')});$$('.mv-delete').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.vi),v=arr[i];if(!v)return;if(!confirm(`Padam versi "${v.name}"? Tindakan ini tidak boleh diundur.`))return;arr.splice(i,1);await saveProject();toast('Versi manuskrip dipadam.');renderProject('versions')})};
const mvStyle=document.createElement('style');mvStyle.textContent=`.manuscript-version-row{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line)}.mv-main{min-width:0}.mv-main b,.mv-main span{display:block}.mv-main span{font-size:12px;color:var(--muted);margin-top:4px}.mv-main p{margin:7px 0 0;color:var(--muted);font-size:13px}.mv-actions{display:flex;gap:8px;flex-wrap:wrap}.danger-soft{color:#b42318;background:#fff5f4;border-color:#ffd7d2}.mv-preview-head h2{margin-bottom:4px}.mv-preview-head p{margin-top:0;color:var(--muted)}.mv-note{background:#faf9ff;border:1px solid #eee9ff;border-radius:12px;padding:12px;margin-bottom:16px}.mv-preview{max-height:58vh;overflow:auto;border-top:1px solid var(--line)}.mv-preview-section{padding:18px 0;border-bottom:1px solid var(--line)}.mv-preview-section h3{margin:0 0 10px}.mv-preview-section div{line-height:1.7}@media(max-width:650px){.manuscript-version-row{align-items:flex-start;flex-direction:column}.mv-actions{width:100%}.mv-actions .btn{flex:1}}`;document.head.appendChild(mvStyle);
