// V1.6 — Editable Manuscript Versions
const _v16OpenPreview=openManuscriptPreview;
function editVersionDialog(v){
  const p=state.current, keys=Object.keys(v.content||{});
  const sections=keys.map((k,i)=>`<div class="mve-section"><label>${escapeHtml(k)} <small><span id="mveCount${i}">${sectionWordCount(v.content[k])}</span> perkataan</small></label><div id="mve${i}" class="mve-editor" contenteditable="true">${v.content[k]||''}</div></div>`).join('');
  modal(`<div class="mve-head"><div><h2>Edit Versi Manuskrip</h2><p>Perubahan di sini hanya mengemas kini versi ini. Manuskrip semasa tidak berubah sehingga anda memilih Pulihkan/Jadikan Manuskrip Semasa.</p></div></div><label>Nama versi<input id="mveName" value="${escapeHtml(v.name||'Versi Manuskrip')}"></label><label>Catatan<textarea id="mveNote">${escapeHtml(v.note||'')}</textarea></label><label>Status<select id="mveStatus"><option>Draft</option><option>Review</option><option>Revision</option><option>Final</option></select></label><div class="mve-scroll">${sections}</div><div class="actions"><button class="btn" onclick="closeModal()">Tutup</button><button class="btn" id="mveCurrent">Jadikan Manuskrip Semasa</button><button class="btn primary" id="mveSave">Simpan Perubahan Versi</button></div>`);
  $('#mveStatus').value=v.status||'Draft';
  keys.forEach((k,i)=>{$(`#mve${i}`).addEventListener('input',()=>{$(`#mveCount${i}`).textContent=sectionWordCount($(`#mve${i}`).innerHTML)})});
  $('#mveSave').onclick=async()=>{v.name=$('#mveName').value.trim()||v.name;v.note=$('#mveNote').value.trim();v.status=$('#mveStatus').value;v.edited_at=new Date().toISOString();keys.forEach((k,i)=>v.content[k]=$(`#mve${i}`).innerHTML);await saveProject();toast('Perubahan versi manuskrip disimpan.');closeModal();renderProject('versions')};
  $('#mveCurrent').onclick=async()=>{if(!confirm('Jadikan versi ini sebagai manuskrip semasa? Kandungan manuskrip semasa akan digantikan.'))return;p.content=structuredClone(v.content||{});p.outline=structuredClone(v.outline||p.outline||[]);p.checklist=structuredClone(v.checklist||p.checklist||[]);await saveProject();toast('Versi ini kini menjadi manuskrip semasa.');closeModal();renderProject('write')};
}
openManuscriptPreview=function(v){const sections=Object.entries(v.content||{}).map(([k,val])=>`<section class="mv-preview-section"><h3>${escapeHtml(k)}</h3><div>${val||'<em>Belum ditulis</em>'}</div></section>`).join('');modal(`<div class="mv-preview-head"><div><h2>${escapeHtml(v.name||'Versi Manuskrip')}</h2><p>${new Date(v.at).toLocaleString('ms-MY')} · ${versionWords(v).toLocaleString()} perkataan · ${escapeHtml(v.status||'Draft')}</p>${v.edited_at?`<p>Terakhir diedit: ${new Date(v.edited_at).toLocaleString('ms-MY')}</p>`:''}</div></div>${v.note?`<div class="mv-note"><b>Catatan:</b> ${escapeHtml(v.note)}</div>`:''}<div class="mv-preview">${sections}</div><div class="actions"><button class="btn" onclick="closeModal()">Tutup</button><button class="btn primary" id="mvEditOpened">Edit Versi Ini</button></div>`);$('#mvEditOpened').onclick=()=>editVersionDialog(v)};
const _v16VersionView=versionView;
versionView=function(){const html=_v16VersionView();return html.replace(/(<b>[^<]+<\/b><span>[^<]+)(<\/span>)/g,(m,a,b)=>a+' · status disimpan'+b)};
const mveStyle=document.createElement('style');mveStyle.textContent=`.mve-scroll{max-height:52vh;overflow:auto;margin-top:14px;border-top:1px solid var(--line)}.mve-section{padding:14px 0;border-bottom:1px solid var(--line)}.mve-section label{font-weight:700;display:flex;justify-content:space-between}.mve-section small{font-weight:400;color:var(--muted)}.mve-editor{min-height:130px;padding:14px;border:1px solid var(--line);border-radius:10px;background:#fff;line-height:1.7;outline:none}.mve-editor:focus{border-color:#8b7cf6;box-shadow:0 0 0 3px rgba(139,124,246,.12)}`;document.head.appendChild(mveStyle);
