/* Naskhah Studio versions module */
(()=>{
 const clone=x=>JSON.parse(JSON.stringify(x));
 const versionWords=v=>Object.values(v?.content||{}).reduce((n,x)=>n+countWords(x),0);
 function enhancedVersionsView(p){
   const arr=p.goals?.versions||[];
   return `<div class="card"><div class="card-head"><div><h2>Versions / Simpan Manuskrip</h2><p class="muted">Simpan versi manuskrip, buka semula, edit, rename, simpan perubahan atau buang versi.</p></div><button class="btn primary" id="saveVersion">Simpan Manuskrip</button></div>${arr.length?arr.slice().reverse().map((v,ri)=>{const i=arr.length-1-ri;return `<div class="version-row"><div><b>${esc(v.name||'Manuskrip')}</b><div class="muted">${new Date(v.updated_at||v.at).toLocaleString('ms-MY')} · ${versionWords(v).toLocaleString()} perkataan · ${esc(v.status||'Draft')}</div></div><div class="actions"><button class="btn small" data-editver="${i}">Buka / Edit</button><button class="btn small" data-renamever="${i}">Rename</button><button class="btn small danger" data-delver2="${i}">Buang</button></div></div>`}).join(''):'<p class="muted">Belum ada manuskrip disimpan.</p>'}</div>`;
 }
 function openVersionEditor(p,i){
   const v=p.goals.versions[i]; if(!v)return;
   const content=clone(v.content||{}), sections=Object.keys(content); let active=sections[0]||'';
   const render=()=>{modal(`<div class="card-head"><div><h2>Edit Versi: ${esc(v.name||'Manuskrip')}</h2><p class="muted">Versi ini berasingan daripada manuskrip semasa sehingga anda pilih Apply to Current Manuscript.</p></div></div><div class="version-editor-grid"><aside class="section-list version-section-list">${sections.map(s=>`<button data-vsec="${esc(s)}" class="${s===active?'active':''}">${esc(s)}<small>${countWords(content[s])} words</small></button>`).join('')}</aside><section class="editor-card version-editor-card"><div class="editor-head"><h2>${esc(active)}</h2><span class="type-pill" id="verWordCount">${countWords(content[active])} words</span></div><div id="versionEditor" class="rich-editor" contenteditable="true" spellcheck="true">${content[active]||''}</div></section></div><div class="grid2"><label>Nama Versi<input id="editVersionName" value="${esc(v.name||'Manuskrip')}"></label><label>Status<select id="editVersionStatus"><option>Draft</option><option>Supervisor Review</option><option>Revision</option><option>Final Draft</option><option>Submitted</option><option>Archived</option></select></label></div><div class="actions"><button class="btn" id="closeVersionEdit">Tutup</button><button class="btn" id="saveAsNewVersion">Save as New Version</button><button class="btn" id="applyVersion">Apply to Current Manuscript</button><button class="btn primary" id="saveVersionChanges">Simpan Perubahan</button></div>`);
     $('#editVersionStatus').value=v.status||'Draft';
     const ed=$('#versionEditor'); ed.oninput=()=>{content[active]=ed.innerHTML;$('#verWordCount').textContent=countWords(ed.innerHTML)+' words'};
     $$('[data-vsec]').forEach(b=>b.onclick=()=>{content[active]=ed.innerHTML;active=b.dataset.vsec;render()});
     $('#closeVersionEdit').onclick=closeModal;
     $('#saveVersionChanges').onclick=async()=>{content[active]=ed.innerHTML;v.name=$('#editVersionName').value.trim()||v.name||'Manuskrip';v.status=$('#editVersionStatus').value;v.content=clone(content);v.updated_at=new Date().toISOString();await saveProject();closeModal();toast('Perubahan versi manuskrip disimpan.');renderProject('versions')};
     $('#saveAsNewVersion').onclick=async()=>{content[active]=ed.innerHTML;p.goals.versions.push({name:($('#editVersionName').value.trim()||v.name||'Manuskrip')+' - Copy',status:$('#editVersionStatus').value,at:new Date().toISOString(),updated_at:new Date().toISOString(),content:clone(content),outline:clone(v.outline||p.outline),checklist:clone(v.checklist||p.checklist)});await saveProject();closeModal();toast('Versi baharu disimpan.');renderProject('versions')};
     $('#applyVersion').onclick=async()=>{content[active]=ed.innerHTML;if(!confirm('Gunakan versi ini sebagai manuskrip semasa? Kandungan manuskrip semasa akan digantikan.'))return;p.content=clone(content);if(v.outline)p.outline=clone(v.outline);if(v.checklist)p.checklist=clone(v.checklist);await saveProject();closeModal();toast('Versi digunakan sebagai manuskrip semasa.');renderProject('writing')};
   }; render();
 }
 window.versionsView=enhancedVersionsView;
 const oldBindTab=window.bindTab||bindTab;
 window.bindTab=function(tab){oldBindTab(tab);if(tab==='versions'){
   const p=state.current;
   const save=$('#saveVersion');if(save)save.onclick=()=>{modal(`<h2>Simpan Manuskrip</h2><label>Nama versi<input id="verName" value="Manuskrip ${(p.goals.versions||[]).length+1}"></label><label>Status<select id="verStatus"><option>Draft</option><option>Supervisor Review</option><option>Revision</option><option>Final Draft</option><option>Submitted</option><option>Archived</option></select></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="confirmVersion2">Simpan</button></div>`);$('#confirmVersion2').onclick=async()=>{p.goals.versions.push({name:$('#verName').value.trim()||'Manuskrip',status:$('#verStatus').value,at:new Date().toISOString(),updated_at:new Date().toISOString(),content:clone(p.content),outline:clone(p.outline),checklist:clone(p.checklist)});await saveProject();closeModal();toast('Manuskrip disimpan.');renderProject('versions')}};
   $$('[data-editver]').forEach(b=>b.onclick=()=>openVersionEditor(p,Number(b.dataset.editver)));
   $$('[data-renamever]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.renamever),v=p.goals.versions[i];modal(`<h2>Rename Version</h2><label>Nama versi<input id="renameVersionInput" value="${esc(v.name||'Manuskrip')}"></label><div class="actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="renameVersionSave">Simpan</button></div>`);$('#renameVersionSave').onclick=async()=>{v.name=$('#renameVersionInput').value.trim()||v.name;v.updated_at=new Date().toISOString();await saveProject();closeModal();renderProject('versions')}});
   $$('[data-delver2]').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.delver2);if(!confirm('Buang versi manuskrip ini?'))return;p.goals.versions.splice(i,1);await saveProject();toast('Versi dibuang.');renderProject('versions')});
 }};
})();